Site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#import reset

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^reset/', include('reset.urls')),
    url(r'', include('papers.urls', namespace='papers')),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +\
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

papers/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<slug>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[0-9]+)/pdf/$', views.DownloadPdf, name='download'),
    url(r'^author/(?P<investigator>[-\w]+)/$', views.IndexView.as_view(), name='query'),
    url(r'^date/(?P<date>[-\w]+)/$', views.IndexView.as_view(), name='query'),
    url(r'^query/$', views.IndexView.as_view(), name='search'),
    url(r'^papers-with-missing-pdfs/$', views.MissingPdfs.as_view()),
    url(r'^add-paper/$', views.AddPmidForm),
    url(r'^submit-pmid/$', views.SubmitPmid, name='submit-pmid'),
]

papers/models.py
from django.db import models



class Paper(models.Model):
    def __unicode__(self):
        return self.pmid
    title = models.CharField(max_length=1000)
    journal = models.CharField(max_length=1000)
    pub_date = models.DateTimeField()
    pmid = models.CharField(max_length=12, blank=True, null=True)
    abstract = models.TextField(default="", blank=True)
    volume = models.CharField(max_length=200, blank=True)
    issue = models.CharField(max_length=200, blank=True)
    start_page = models.CharField(max_length=200, blank=True)
    end_page = models.CharField(max_length=200, blank=True)
    journal_abbreviation = models.CharField(max_length=200)
    doi = models.CharField(max_length=200, blank=True)
    slug = models.SlugField()
    pdf = models.FileField(upload_to='publication_pdfs', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
 


class Author(models.Model):
    def __unicode__(self):
        return self.name
    paper = models.ManyToManyField(Paper, through='AuthorOrder')
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    forename = models.CharField(max_length=200, blank=True, null=True)
    initials = models.CharField(max_length=200, blank=True, null=True)
    featured_author = models.BooleanField(default=False)
    slug = models.SlugField(default='1')
    
    
class Affiliation(models.Model):
    def __unicode__(self):
        return self.name
    author = models.ManyToManyField(Author)
    name = models.CharField(max_length=1000)


class AuthorOrder(models.Model):
    number = models.IntegerField()
    paper = models.ForeignKey(Paper)
    author = models.ForeignKey(Author)

papers/views.py
from datetime import datetime

from django.shortcuts import render,get_object_or_404, render_to_response
from django.template import RequestContext
from django.views import generic
from django.conf import settings
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Paper, Author

from management.commands import add_by_pmid 


class IndexView(generic.ListView):
    template_name = 'papers/index.html'
    context_object_name = 'paper_list'
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(IndexView, self).get_context_data(**kwargs)
        # Add in the publisher
        context['featured_authors'] = Author.objects.filter(featured_author=True).order_by('surname')
        context['paper_years'] = [str(i) for i in reversed(sorted(set([p.pub_date.year for p in Paper.objects.only('pub_date')])))]
        context['current_query'] = self.request.GET
        if ('investigator' in self.request.GET): 
            context['selected_investigator'] = Author.objects.get(slug= self.request.GET['investigator'].strip())
        return context
    
    def get_queryset(self):
        entry_query=Paper.objects.all()
        if 'investigator' in self.kwargs:
            self.investigator = get_object_or_404(Author, slug=self.kwargs['investigator'])
            #filters['author'] = self.investigator
            entry_query = entry_query.filter(author=self.investigator)
            print len(entry_query)
        if ('investigator' in self.request.GET) and self.request.GET['investigator'].strip():
            entry_query = entry_query.filter(author__slug=self.request.GET['investigator'])
        if ('date' in self.request.GET) and self.request.GET['date'].strip():
            entry_query = entry_query.filter(pub_date__year=self.request.GET['date'])
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            self.query_string = self.request.GET['q']
            entry_query = entry_query.filter(get_query(self.query_string, ['title', 'journal', 'author__name'])).distinct()
        
        return entry_query.order_by('-pub_date')
        #return Paper.objects.filter(**filters).order_by('-pub_date')

class MissingPdfs(IndexView):
    
    def get_queryset(self):
        return [ paper for paper in Paper.objects.order_by('-pub_date') if bool(paper.pdf) == False]

#@login_required(login_url='/admin/login/')
@login_required()
def AddPmidForm(request):
   return render_to_response('papers/add_paper.html')

def SubmitPmid(request):
    pmid = request.GET['q']
    p = add_by_pmid.download_and_parse_pubmed(pmid)

    #return HttpResponse("Added PMID: {}".format(pmid))
    return HttpResponseRedirect(reverse('admin:papers_paper_change', args= (str(p.id),)))

        
        
        

#XXX Depricated
class QueryView(generic.ListView):
    template_name = 'papers/index.html'
    context_object_name = 'paper_list'
   
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(QueryView, self).get_context_data(**kwargs)
        # Add in the publisher
        context['investigator'] = self.investigator
        return context
   
    
    def get_queryset(self):
        self.investigator = get_object_or_404(Author, slug=self.kwargs['investigator'])
        return Paper.objects.filter(author=self.investigator).order_by('-pub_date')


class DetailView(QueryView):
    template_name = 'papers/index.html'
    context_object_name = 'paper_list'
   
    def get_context_data(self, **kwargs):
        context = super(QueryView, self).get_context_data(**kwargs)
        context['show_abstract'] = True
        return context
     
    def get_queryset(self):
        return Paper.objects.filter(slug=self.kwargs['slug'])

def DownloadPdf(request, slug):
    paper = get_object_or_404(Paper, slug=slug)
    
    # check to see if the paper exists
    if paper.pdf:
    
        # nationalize the name
        name = '{name}_{year}_{journal}_{pmid}'.format(**{'name':paper.author_set.all()[0].surname.lower(),
                          'journal':paper.journal_abbreviation.replace(' ','-').lower().replace('.',''),
                          'year':str(paper.pub_date.year),
                          'pmid':paper.pmid,})
        
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="%s.pdf"'%(name)
        response.write(file(paper.pdf.file.name, "rb").read())
        return response
    
    else:
        return HttpResponse('no pdf attached for this paper')
   

import re

from django.db.models import Q

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:
        
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
    
    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)] 



def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.
    
    '''
    query = None # Query to search for every search term        
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query


class search(IndexView):
    template_name = 'papers/index.html'
    context_object_name = 'paper_list'

    def post(self, request):
        return self.get(request, self.get_queryset_post())

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(search, self).get_context_data(**kwargs)
        context['query_string'] = self.query_string
        return context


    def get_queryset_post(self):
        self.query_string = self.request.POST['q']
        
        entry_query = get_query(self.query_string, ['title', 'journal',
        'author__name'])
        
        return Paper.objects.filter(entry_query).order_by('-pub_date').distinct()

    def get_queryset(self):
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            self.query_string = self.request.GET['q']
        
        entry_query = get_query(self.query_string, ['title', 'journal', 'author__name'])
        
        return Paper.objects.filter(entry_query).order_by('-pub_date').distinct()

papers/templates/papers/add_paper.html
Add by PMID (e.g., 27592001):<form action="{% url 'papers:submit-pmid' %}" method="get" >
    <input type="text" name="q" id="id_q" placeholder="<PMID>"/>
    <input type="submit" value="Search"
    style="position: absolute; left: -9999px; width: 1px; height: 1px;"
       tabindex="-1" />
</form>


<a href="{% url 'admin:papers_paper_add' %}">Add manually</a>

papers/templates/papers/add_pmid.html
<form action="{% url 'papers:submit-pmid' %}" method="get" >
    <input type="text" name="q" id="id_q" placeholder="<PMID>"/>
    <input type="submit" value="Search"
    style="position: absolute; left: -9999px; width: 1px; height: 1px;"
       tabindex="-1" />
</form>

papers/templates/papers/detail.html
{% extends "index.html" %}


{% block postdata %}
    {{ paper.abstract }}
{% endblock %}

papers/templates/papers/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load add_get_parameter %} 
{% load humanize %} 
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>ScitoVation</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'papers/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'papers/css/landing-page.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'papers/css/style.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'papers/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body data-spy="scroll" data-target="#teamYearGroup" data-offset="20">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
      <div class="container-fluid topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnavLogo" href="http://scitovation.com">
                <img style="width: 140px; height: auto; margin-top: -8px; margin-left: 5px; padding-left: -35px;" src="{% static 'papers/img/scitovation_logo_medium_res.png' %}" alt="ScitoVation">
                <!--<img src="img/scitovation-small.png">-->
              </a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right" id="sciNavbar">
                  <li class="hoverColor">
                      <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                      <a href="about.html">About Us</a>
                  </li>
                  <li class="hoverColor">
                      <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
                      <a href="whatwedo.html">What We Do</a>
                  </li>
                  <li class="hoverColor">
                      <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
                      <a href="whoWeServe.html">Who We Serve</a>
                  </li>
                  <li class="hoverColor">
                      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                      <a href="careers.html">Careers</a>
                  </li>
                  <li class="hoverColor">
                      <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                      <a href="research.html">Research</a>
                  </li>
                  <li class="hoverColor">
                      <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                      <a href="contact.html">Contact Us</a>
                  </li>
              </ul>
          </div>
      </div>
  </nav>
  <br /><br /><br /> <!--NEED TO DO MARGIN/PADDING INSTEAD-->
  <!-- End Navigation -->


<!-- ========================================================================== --!>
<!-- AUTHOR --!>
<ul>
{% for author in featured_authors %}
    <li>
        {% if author.slug == current_query.investigator %}
            <strong><a href="{% url 'papers:index' %}{% add_get investigator='' page=1%}">{{ author.name }}</a></strong>
        {% else %}
            <a href="{% url 'papers:index' %}{% add_get investigator=author.slug page=1%}">{{ author.name }}</a>
        {% endif %}
    </li>
{% endfor %}
</ul>
{% if current_query.investigator %}
<a class="clear" href="{% url 'papers:index' %}{% add_get investigator='' %}">clear author filter</a>
{% else %}
<a class="clear"><br></a>
{% endif %}




<!-- ========================================================================== -->
<!-- CONTENT -->
{% block content %}
  <div class="container" id="fluidContainer">
      <!-- Page Heading -->
      <div class="row">
          <div class="col-lg-12">
              <h1 class="page-header">Research and Publications
                  <small></small>
              </h1>
              <ol class="breadcrumb" id="breadcrumbBanner">
                  <li><a href="index.html">Home</a>
                  </li>
                  <li class="active">Research</li>
              </ol>
          </div>
      </div>

      <!-- Content Row -->
            <div class="row">
              <div class="col-lg-3">
                  <div class="list-group" id="teamListGroup">

                        <!-- ========================================================================== -->
                        <!-- AUTHOR -->
                        {% for author in hamner_authors %}
                                {% if author.slug == current_query.investigator %}
                                    <strong><a class="list-group-item" href="{% url 'papers:index' %}{% add_get investigator='' page=1%}">{{ author.name }}</a></strong>
                                {% else %}
                                    <a class="list-group-item" href="{% url 'papers:index' %}{% add_get investigator=author.slug page=1%}">{{ author.name }}</a>
                                {% endif %}
                        {% endfor %}
                        {% if current_query.investigator %}
                        <a class="clear" href="{% url 'papers:index' %}{% add_get investigator='' %}">clear author filter</a>
                        {% else %}
                        <a class="clear"><br></a>
                        {% endif %}
                  </div>
                  <hr>
                </div>
                <div class="col-lg-7">
                    <div class="panel-group" id="accordion">
                        {% for paper in paper_list %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">
                                        {{ paper.title }} 
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
                                <div class="panel-body">
                                  <li class="alternating">
                                        {% for author in paper.author_set.all %}
                                            {% if not forloop.last %}
                                                <a href="{% url 'papers:index' %}?investigator={{author.slug}}">{{ author.initials }} {{ author.surname }}</a>,
                                            {% else %}
                                                {% if paper.author_set.all|length > 1 %}
                                                    and 
                                                {% endif %}
                                                <a href="{% url 'papers:index' %}?investigator={{author.slug}}">{{ author.initials }} {{ author.surname }}</a>.
                                            {% endif %}
                                        {% endfor %}
    {{ paper.title }} 
    <i>{{ paper.journal_abbreviation }}</i> 
    <b>{{ paper.volume }}</b>
    {% if paper.issue %}
        ({{ paper.issue }})
    {% endif %}

    {% if paper.start_page %}: {{ paper.start_page }}
        {% if paper.end_page%}
            -{{ paper.end_page}}
        {% endif %}
    {% endif %}

    ({{ paper.pub_date|date:"M j, Y"}}).
    [<a href="{% url 'papers:detail' slug=paper.slug %}">abstract</a>]
    {% if paper.pmid %}
        [<a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ paper.pmid }}">pubmed</a>]
    {% endif %}
    {% if show_abstract %}
    	<p> {{ paper.abstract }} </p>
    {% endif %}
                                  </li>
                            </div>
                        </div>
                            </div>
                        {% endfor %}

<!-- ========================================================================== -->
<!-- PAGINATION -->
<div id="pagination">
{% if page_obj.has_previous %}
    <a  href="{% url 'papers:index' %}{% add_get page=page_obj.previous_page_number %}">previous</a>
{% endif %}
{% if page_obj.has_next %}
    <a  href="{% url 'papers:index' %}{% add_get page=page_obj.next_page_number %}">next</a>
{% endif %}
</div>

                       
                      </div>
                  </div>
                </div>
            </div>
            <hr>


{% endblock %}


            <!-- Footer -->
            <footer id="mainFooter">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-inline">
                                <li>
                                    <a href="index.html">Home</a>
                                </li>
                                <li class="footer-menu-divider">&sdot;</li>
                                <li>
                                    <a href="about.html">About Us</a>
                                </li>
                                <li class="footer-menu-divider">&sdot;</li>
                                <li>
                                    <a href="whatWeDo.html">What We Do</a>
                                </li>
                                <li class="footer-menu-divider">&sdot;</li>
                                <li>
                                    <a href="whoWeServe.html">Who We Serve</a>
                                </li>
                                <li class="footer-menu-divider">&sdot;</li>
                                <li>
                                    <a href="careers.html">Careers</a>
                                </li>
                                <li>
                                    <a href="research.html">Research</a>
                                </li>
                                <li class="footer-menu-divider">&sdot;</li>
                                <li>
                                    <a href="contact.html">Contact Us</a>
                                </li>
                            </ul>
                            <p class="copyright text-muted small">Copyright &copy; ScitoVation. All Rights Reserved</p>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- End Footer -->


            <!-- jQuery -->
            <script src="{% static 'papers/js/jquery.js' %}"></script>
            <!-- Bootstrap Core JavaScript -->
            <script src="{% static 'papers/js/bootstrap.min.js' %}"></script>

            <script scr="research.html">
              $('body').scrollspy({ target: '#teamListGroup' });

              $('[data-spy="scroll"]').each(function () {
                var $spy = $(this).scrollspy('refresh')
              })
            </script>


            </body>
            </html>